### ISSUE TITLE
ZAH 0.5

### ISSUE THREAD

**Issue by leventov** [benalexau/hash-bench#2]
ZAH 0.5 is released. It has no changes compared to the version benchmarked, so the tests shouldn't be re-run, just running/building process simplified, depending on the release 0.5 version.

**Comment by benalexau** [comment]
Thanks for letting me know.

POM updated in 332b716697985e1ef960f86e1fef9f29b430ca07.

I'll run the benchmark again anyway, as I have updated to Java 1.8.0_66 and Linux 4.2.5 since the last report.

**Comment by benalexau** [comment]
6f7eae2 adds report #5, including the aforementioned Java 1.8.0_66 and Linux 4.2.5, plus also updating the new latest JMH 1.11.2.
